### ISSUE TITLE
ROS2 Support

### ISSUE THREAD

**Issue by fladdie** [belovictor/odrive_can_ros_driver#1]
Hello it would be great if someone could make a port to ROS 2.

**Comment by belovictor** [comment]
@fladdie indeed it will be great. Unfortunately I neither have experience in working with ROS2 nor knowledge on how to build packages working both with ROS1 and ROS2, so I can't do it currently but would be happy to accept pull request for that!

**Comment by belovictor** [comment]
As odriverobotics now provide official ROS2 package I'm closing this.
[https://docs.odriverobotics.com/v/latest/guides/ros-package.html](https://docs.odriverobotics.com/v/latest/guides/ros-package.html)
