### ISSUE TITLE
Request for publication of wiring diagrams

### ISSUE THREAD

**Issue by Ramune6110** [belovictor/odrive_can_ros_driver#2]
Hello!
Thank you very much for publishing your excellent code.
Now, I have no idea what kind of wiring I need to do to actually check the operation.
 (Wiring relationship between Raspberry Pi, CAN HAT and Odrive)
If possible, could you please include a simple wiring diagram in the README?
Thank you in advance.

**Comment by belovictor** [comment]
Hi!

General CAN principals and wiring are well described in ODrive documentation:
[https://docs.odriverobotics.com/v/0.6.0/can-guide.html](https://docs.odriverobotics.com/v/0.6.0/can-guide.html)
so I don't really see a reason to duplicate it here.

Best regards,
Victor Belov
